name             'yum-osuosl'
maintainer       'Oregon State University'
maintainer_email 'chef@osuosl.org'
source_url       'https://github.com/osuosl-cookbooks/yum-osuosl'
issues_url       'https://github.com/osuosl-cookbooks/yum-osuosl/issues'
license          'Apache-2.0'
chef_version     '>= 16.0'
description      'Installs/Configures yum-osuosl'
version          '2.1.1'

supports         'almalinux', '~> 8.0'
supports         'almalinux', '~> 9.0'
